main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('about_us/', views.about_us, name='about_us'),
    path('balance/', views.balance_add, name='balance_add'),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('fill-database/', views.fill_database, name='fill_database'),
    path('', views.ProductsListView.as_view(), name='shop'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('detail/<int:pk>/', views.ProductsDetailView.as_view(), name='shop_detail'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart, name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(), name='cart_delete_item'),
    path('make-order/', views.make_order, name='make_order'),
]

shop/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='product_name')
    code = models.CharField(max_length=255, verbose_name='product_code')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.CharField(max_length=255, blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name} - {self.price}'


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return f'{self.user} - {self.amount}'

    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class Order(models.Model):
    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None

        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0)
        return cart

    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount

    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpaid_orders(self.user)

    @staticmethod
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.product} - {self.price}'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)


@transaction.atomic()
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user,
                                         status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user,
                               amount=-order.amount)


@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpaid_orders(user)

shop/forms.py
from django import forms

from .models import OrderItem


class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, DeleteView
from .scraping import scraping, ScrapingError
from .models import Product, Order, OrderItem
from .forms import AddQuantityForm


def fill_database(request):
    if request.method == 'POST' and request.user.is_staff:
        try:
            scraping()
        except ScrapingError as err:
            print(str(err))
            return render(request, 'shop/fill-products.html', {'message': str(err)})
    return render(request, 'shop/fill-products.html', {'message': None})


class ProductsListView(ListView):
    model = Product
    template_name = 'shop/shop.html'


class ProductsDetailView(DetailView):
    model = Product
    template_name = 'shop/shop-details.html'


@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                # product = Product.objects.get(pk=pk)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('cart_view')
        else:
            pass
    return redirect('shop')


@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/cart.html', context)


@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('cart_view')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs


@login_required(login_url=reverse_lazy('login'))
def make_order(request):
    cart = Order.get_cart(request.user)
    cart.make_order()
    return redirect('shop')

templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   Cart
{% endblock title %}

{% block container %}

<!-- content start -->
  <div class="main-content-wrapper">
       <section class="breadcrumbs-custom bg-image" style="background-image: url('{% static 'images/bg-image-2.jpg' %}');">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-5">
                      <div class="breadcrumb-wrapper">
                          <h2>Корзина</h2>
                          <ul class="breadcrumbs-custom__path">
                              <li><a href="{% url 'shop' %}">Товары</a></li>
                              <li class="active">Корзина</li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
       </section>


      <section class="selection">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-9">
                      <div class="main-heading-block">
                          <h2 class="main-heading"></h2>
                          <!-- <p>EXERCITATIONEM ULLAM CORPORIS</p> -->
                      </div>
                  </div>
              </div>
              <hr class="hr"/>
              <div class="row" style="color:black">
                  <div class="col-12 col-md-1 item"><b>#</b>
                  </div>
                  <div class="col-12 col-md-4 item"><b>Товар</b>
                  </div>
                  <div class="col-12 col-md-2 item"><b>Количество, шт</b>
                  </div>
                  <div class="col-12 col-md-2 item"><b>Цена, руб</b>
                  </div>
                  <div class="col-12 col-md-2 item"><b>Сумма, руб</b>
                  </div>
                  <div class="col-12 col-md-1 item"><b>Действие</b>
                  </div>
              </div>
              <hr class="hr"/>
                    {% if not items %}
                        <br><br>
                        <div class="col-12 col-md-10 item">
                            <h2 style="color:black">В вашей корзине отсутствуют товары!</h2>
                        </div>
          </div>
                    <br><br>
                    {% else %}
                    {% for item in items %}
                    <div class="row" style="color: black">
                        <div class="col-12 col-md-1 item">
                            {{ forloop.counter }}
                        </div>
                        <div class="col-12 col-md-4 item">
                            {{ item.product }}
                        </div>
                        <div class="col-12 col-md-2 item">
                            {{ item.quantity }}
                        </div>
                        <div class="col-12 col-md-2 item">
                            {{ item.price }}
                        </div>
                        <div class="col-12 col-md-2 item">
                            {{ item.amount }}
                        </div>
                         <div class="col-12 col-md-1 item">
                             <form method="post" action="{% url 'cart_delete_item' item.pk %}">
                                {% csrf_token %}
                                <button type="submit" style="color: #FF0000"><u>delete</u></button>
                            </form>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
            <hr class="hr"/>

          <div class="row" style="color:#FF9A00">
              <div class="col-12 col-md-7 item"></div>
              <div class="col-12 col-md-2 item"><b>Итоговая сумма:</b>
              </div>
              <div class="col-12 col-md-2 item"><b>
                    {{ cart.amount }} руб.</b>
              </div>
          </div>


          <hr class="hr"/>
          {% if not items %}
          <div class="row" style="color:#FF9A00">
              <div class="col-12 col-md-8  item"></div>
              <div class="col-12 col-md-2 item">
                 <a class="button button-xs button-lighter" href="{% url 'shop' %}">
                    Перейти к товарам
                    </a>
              </div>
          </div>
          {% else %}
          <div class="row" style="color:#FF9A00">
              <div class="col-12 col-md-8  item"></div>
              <div class="col-12 col-md-2 item">
                 <a class="button button-xs button-lighter" href="{% url 'shop' %}">
                        Перейти к Товарам
                 </a>
              </div>
              <div class="col-12 col-md-2 item">
                  <a class="button button-xs button-lighter" href="{% url 'make_order' %}">
                        Оплатить
                  </a>
              </div>
          </div>
          {% endif %}
      </section>
  </div>
      {% endblock container %}

templates/shop/fill-products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   Fill Products
{% endblock title %}

{% block container %}

    <!-- content start -->
    <div class="main-content-wrapper">
        <section class="breadcrumb-section about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-5">
                        <div class="breadcrumb-wrapper">
                            <h2>Наполнить товары</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div>
        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg5 col-md-5"></div>
                    <div class="col-lg-7 col-mg-7">
                        <div class="main-heading-block">
                            <form method="post" action="{% url 'fill_database' %}">
                                {% csrf_token %}
                                <button class="button button-xs button-lighter" name="fill_database" type="submit" onclick="runSpinner()">
                                    <span class="spinner spinner-border spinner-border-sm" role="status" id="spinner"
                                          style="color:red" aria-hidden="true"></span>
                                    Начать
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {% if message %}
            <div class="container">
                <div class="row">
                    <div class="main-heading-block">
                        <h2>Errors of scraping: <br><br>
                            <span style="color:red"> {{message}}</span>
                        </h2>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    <br><br><br><br><br>
        <!-- content end -->
{% endblock container %}

templates/shop/shop-details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   Shop-details
{% endblock title %}

{% block container %}
<!-- content start -->
  <div class="main-content-wrapper">
       <section class="breadcrumbs-custom bg-image" style="background-image: url('{% static 'images/bg-image-3.jpg' %}');">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-5">
                      <div class="breadcrumb-wrapper">
                          <h2>Информация о товаре</h2>
                          <ul class="breadcrumbs-custom__path">
                              <li><a href="{% url 'shop' %}">Товары</a></li>
                              <li class="active">Информация о товаре</li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
        </section>


      <section class="selection">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-9">
                      <div class="main-heading-block">
                          <h2 class="main-heading"></h2>
                          <!-- <p>EXERCITATIONEM ULLAM CORPORIS</p> -->
                      </div>
                  </div>
              </div>
              <div class="row">
                  <div class="col-12 col-lg-4 col-md-3 item"></div>
                  <div class="col-12 col-lg-4 col-md-6 item">

                      <div class="card" style="color:#FF9A00">
                          <img src="{{product.image_url}}" class="card-img-top" alt="color:#FF9A00">
                                <div class="card-body">
                                    <h5 class="card-title"><b>{{ product.name }}</b></h5>
                                        <p class="card-text">
                                        {{ product.description }}
                                        </p>

                                </div>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><b>Код товара: {{ product.code }}</b></li>
                                        <li class="list-group-item"><b>Цена: {{ product.price }} руб.</b></li>
                                    </ul>
                                <div class="card-body">
                                        <a class="button button-xs button-lighter" href="{% url 'shop' %}">К товарам</a>
                                        <a class="button button-xs button-lighter" href="{% url 'contacts' %}">Купить</a>
                                </div>
                                </div>

                  </div>
              </div>
          </div>
      </section>
  </div>

      {% endblock container %}

templates/shop/shop.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   Shop
{% endblock title %}

{% block container %}

<!-- content start -->
  <div class="main-content-wrapper">
       <section class="breadcrumbs-custom bg-image" style="background-image: url('{% static 'images/bg-image-1.jpg' %}');">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-5">
                      <div class="breadcrumb-wrapper">
                          <h2>Товары</h2>
                          <ul class="breadcrumbs-custom__path">
                              <li><a href="{% url 'index' %}">Главная</a></li>
                              <li class="active">Товары</li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
        </section>


      <section class="selection">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-12 col-lg-9">
                      <div class="main-heading-block">
                          <h2 class="main-heading"></h2>
                          <!-- <p>EXERCITATIONEM ULLAM CORPORIS</p> -->
                      </div>
                  </div>
              </div>
              <div class="row">

                {% for product in object_list %}
					<div class="col-12 col-lg-4 col-md-6 item">
                        <div class="card" style="width: 18rem;">
                            <form method="post" action="{% url 'add_item_to_cart' product.pk %}">
                                <img src="{{product.image_url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title"><b>{{ product.name}}</b></h5>
                                    <p class="card-text">
                                        {{ product.description }}
                                    </p>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item" style="color: #FF9A00 "><b>Цена: {{ product.price }} руб.</b></li>
                                    <li class="list-group-item">
										{% csrf_token %}
										<label class="form-label" for="id_quantity">Quantity:</label>
										<input type="number" name="quantity" value="1" min="1"
											   required id="id_quantity"/>
                                    </li>
                                </ul>
                                <div class="card-body">
                                    <button class="button button-xs button-lighter" type="submit">Купить</button>
                                    <a class="button button-xs button-lighter" href="{% url 'shop_detail' product.pk %}">Инфо</a>
                                    <br><br>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endfor %}
              </div>
          </div>
      </section>
  </div>

      {% endblock container %}